import datetime

x = datetime.datetime.now()

print(x.strftime("%B"))
print(x.strftime("%a"))
print(x.strftime("%A"))
print(x.strftime("%w"))
print(x.strftime("%b"))
print(x.strftime("%d"))
print(x.strftime("%m"))
print(x.strftime("%Y"))
print(x.strftime("%y"))
print(x.strftime("%H"))
print(x.strftime("%I"))
print(x.strftime("%M"))
print(x.strftime("%S"))
print(x.strftime("%p"))
print(x.strftime("%F"))
print(x.strftime("%Z"))
print(x.strftime("%U"))
print(x.strftime("%z"))
print(x.strftime("%j"))
print(x.strftime("%W"))
print(x.strftime("%c"))
print(x.strftime("%C"))
print(x.strftime("%X"))
print(x.strftime("%x"))
print(x.strftime("%G"))
print(x.strftime("%u"))
print(x.strftime("%V"))
print(x.strftime("%%"))
